# To override values here make a file named 'Gruntconfig--custom.yml' - it will be git ignored

jsDir: source/js/
jsDest: public/js/
sassDir: source/sass/
sassDest: public/css/
imagesDir: source/images/
bowerDir: bower_components/
